CREATE TABLE users (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `money` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `aff` INT NOT NULL DEFAULT 0,
  `is_admin` INT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login_ip` VARCHAR(255) NOT NULL,
  `last_login_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE server (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `ip` VARCHAR(255) NOT NULL,
  `port` INT NOT NULL DEFAULT 0,
  `key` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `max_limit` INT NOT NULL DEFAULT 0,
  `group` INT NOT NULL DEFAULT 0,
  `storage` VARCHAR(255) NOT NULL,
  `node_name` VARCHAR(255) NOT NULL,
  `network_name` VARCHAR(255) NOT NULL,
  `vm_technology` INT NOT NULL DEFAULT 0, /*1: KVM 2: LXC*/
  `is_nat` INT NOT NULL DEFAULT 0,
  `nat_ip` VARCHAR(255) NOT NULL,
  `status` INT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE use_server (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL DEFAULT 0,
  `server_id` INT NOT NULL DEFAULT 0,
  `hostname` VARCHAR(255) NOT NULL,
  `username` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `type` VARCHAR(255) NOT NULL,
  `max_limit` INT NOT NULL DEFAULT 0,
  `enable` INT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE logs (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL DEFAULT 0,
  `server_id` INT NOT NULL DEFAULT 0,
  `do` VARCHAR(255) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ticket (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `user_id` INT NOT NULL DEFAULT 0,
  `own_admin_id` INT NOT NULL DEFAULT 0,
  `server_id` INT NOT NULL DEFAULT 0,
  `ticket_title` VARCHAR(255) NOT NULL,
  `ticket_body` VARCHAR(255) NOT NULL,
  `is_end` INT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE cart (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `group_id` INT NOT NULL DEFAULT 0,
  `cart_title` VARCHAR(255) NOT NULL,
  `cart_body` VARCHAR(255) NOT NULL,
  `money` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `stock` INT NOT NULL DEFAULT 0,
  `allow_payment` VARCHAR(255) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `payment_id` INT NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL DEFAULT 0,
  `invoice_remote` INT NOT NULL DEFAULT 0,
  `invoice_local` INT NOT NULL DEFAULT 0,
  `money` DECIMAL(10,2) NOT NULL DEFAULT 0.00,
  `pay_status` INT NOT NULL DEFAULT 0, /*1: Paid 2: Unpaid 3: Expired 4: Fraud 5: Cancelled*/
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `end_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE payment (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `type` VARCHAR(255) NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  `pay_id` VARCHAR(255) NOT NULL,
  `key` VARCHAR(255) NOT NULL,
  `private_key` VARCHAR(255) NOT NULL,
  `public_key` VARCHAR(255) NOT NULL,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE setting (
  `site_name` VARCHAR(255) NOT NULL,
  `database_version` INT NOT NULL DEFAULT 0
);

CREATE TABLE announcement (
  `id` INT PRIMARY KEY AUTO_INCREMENT,
  `type` INT NOT NULL DEFAULT 0, /*1: Normal 2: Emergency*/
  `announcement_title` VARCHAR(255) NOT NULL,
  `announcement_body` VARCHAR(255) NOT NULL,
  `display_portal` INT NOT NULL DEFAULT 0,
  `created_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);